# 是否显示非关键警告，例如提示两个附魔不兼容
show-warnings: false

# 是否显示指示插件逻辑错误的严重错误
# 强烈建议保持启用，除非有充分理由禁用
show-errors: true

# 所有铁砧操作的绝对最大等级消耗
max-cost: 256

# 附魔叠加消耗量
enchant-cost-multiplier: 10

# 重命名物品的固定消耗
rename-cost: 1

# 每级经验可修复的耐久量
# 例如：若为 100，则 700/1000 的镐修复需 3 级
durability-per-level: 100

# 修理物品的最低消耗（与耐久无关）
# 更高的值会惩罚如石质工具等廉价物品的修理
min-repair-cost: 3

# 修复物品所需材料数量，基于制作该物品所需的材料数量
# 例如：若为 1，则钻石胸甲完全修复需要 8 个钻石，
# 若为 0.5，则需 4 个钻石完全修复
# 若希望修理比重做更划算，该值应小于 1
material-repair-cost-multiplier: 1

# 是否使用原版的最大等级配置
# 若设为 true，下方的最大等级配置将被忽略
use-vanilla-max-levels: false

# 每个附魔允许的最大等级
# 注意：最大等级为 1 的附魔在更高等级并不会有额外效果，
# 某些附魔在更高等级可能表现异常（如快速装填、冰霜行者等）
# 修改这些配置请自行承担风险
max-level.sharpness: 10             # 锋利
max-level.smite: 10                 # 亡灵杀手
max-level.bane-of-arthropods: 10    # 节肢杀手
max-level.knockback: 10             # 击退
max-level.fire-aspect: 5            # 火焰  
max-level.looting: 8                # 掠夺
max-level.sweeping-edge: 5          # 横扫之刃

max-level.impaling: 10              # 穿刺
max-level.riptide: 5                # 涡流
max-level.loyalty: 5                # 忠诚

max-level.power: 10                 # 力量
max-level.flame: 1                  # 火矢
max-level.punch: 10                 # 冲击
max-level.infinity: 1               # 无尽

max-level.piercing: 8               # 穿透
max-level.quick-charge: 5           # 快速装填
max-level.multishot: 1              # 多重发射

max-level.efficiency: 10            # 效率
max-level.fortune: 8                # 时运  
max-level.silk-touch: 1             # 精准采集

max-level.lure: 5                   # 诱饵
max-level.luck-of-the-sea: 5        # 海之眷顾

max-level.protection: 10            # 保护
max-level.fire-protection: 10       # 火焰保护
max-level.projectile-protection: 10 # 弹射物保护
max-level.blast-protection: 10      # 爆炸保护
max-level.feather-falling: 10       # 摔落保护
max-level.thorns: 5                 # 荆棘
max-level.soul-speed: 5             # 灵魂疾行
max-level.swift-sneak: 5            # 迅捷潜行
max-level.depth-strider: 5          # 深海探索者
max-level.respiration: 5            # 水下呼吸
max-level.aqua-affinity: 1          # 水下速掘
max-level.frost-walker: 4           # 冰霜行者

max-level.unbreaking: 10            # 耐久
max-level.mending: 1                # 修补

max-level.curse-of-binding: 1       # 绑定诅咒
max-level.curse-of-vanishing: 1     # 消失诅咒
